name: Metrics
on:
  schedule: [{cron: "0 3/6 * * *"}]
  push: {branches: "main"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Page Speed
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/metrics.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://www.leoferreira.dev
          plugin_rss: yes
          plugin_rss_source: https://www.leoferreira.dev/rss.xml
          plugin_rss_limit: 4